{{with .Values -}}
{{if .Identity -}}
---
###
### Identity Controller Service
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-identity
  namespace: {{.Namespace}}
---
kind: {{if not .SingleNamespace}}Cluster{{end}}Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-{{.Namespace}}-identity
  {{- if .SingleNamespace}}
  namespace: {{.Namespace}}
  {{- end}}
rules:
- apiGroups: ["extensions", "authentication"]
  resources: ["tokenreview"]
  verbs: ["create"]
---
kind: {{if not .SingleNamespace}}Cluster{{end}}RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-{{.Namespace}}-identity
  {{- if .SingleNamespace}}
  namespace: {{.Namespace}}
  {{- end}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{if not .SingleNamespace}}Cluster{{end}}Role
  name: linkerd-{{.Namespace}}-identity
subjects:
- kind: ServiceAccount
  name: linkerd-identity
  namespace: {{.Namespace}}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-identity
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: identity
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-identity-trust-anchors
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
data:
  trust-anchors.pem: |-
{{indent 4 .Identity.TrustAnchorsPEM}}
{{- if .Identity.Issuer}}
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
    {{- if .Identity.Issuer.ExpiryAnnotation}}
    {{.Identity.Issuer.ExpiryAnnotation}}: {{.Identity.Issuer.Expiry}}
    {{- end}}
data:
  crt.pem: {{b64enc .Identity.Issuer.Crt}}
  key.pem: {{b64enc .Identity.Issuer.Key}}
{{- end}}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: linkerd-identity
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  replicas: {{.IdentityReplicas}}
  template:
    metadata:
      labels:
        {{.ControllerComponentLabel}}: identity
      annotations:
        {{.CreatedByAnnotation}}: {{.CliVersion}}
    spec:
      serviceAccountName: linkerd-identity
      containers:
      - name: identity
        ports:
        - name: grpc
          containerPort: 8080
        - name: admin-http
          containerPort: 9990
        image: {{.ControllerImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        args:
        - "identity"
        - "-addr=:8080"
        - "-admin-addr=:9990"
        - "-log-level={{.ControllerLogLevel}}"
        - "-controller-namespace={{.Namespace}}"
        - "-trust-domain={{.Identity.TrustDomain}}"
        - "-trust-anchors=/var/run/linkerd/identity/trust-anchors/trust-anchors.pem"
        - "-issuer=/var/run/linkerd/identity/issuer"
        - "-issuance-lifetime={{.Identity.IssuanceLifetime}}"
        volumeMounts:
        - mountPath: /var/run/linkerd/identity/trust-anchors
          name: identity-trust-anchors
        - mountPath: /var/run/linkerd/identity/issuer
          name: identity-issuer
        livenessProbe:
          httpGet:
            path: /ping
            port: 9990
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9990
          failureThreshold: 7
        {{- if .EnableHA }}
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
      - name: identity-client
        ports:
        - name: grpc
          containerPort: 8080
        - name: admin-http
          containerPort: 9990
        image: {{.ControllerImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        args:
        - "identity-client"
        - "-addr=localhost:8080"
        - "-log-level=DEBUG"
        - "-name=linkerd-identity.{{.Namespace}}.serviceaccount.identity.{{.Namespace}}.{{.Identity.TrustDomain}}"
        - "-trust-anchors=/var/run/linkerd/identity/trust-anchors/trust-anchors.pem"
        - "-dir=/var/run/linkerd/identity/end-entity"
        - "-token=/var/run/secrets/kubernetes.io/serviceaccount/token"
        volumeMounts:
        - mountPath: /var/run/linkerd/identity/trust-anchors
          name: identity-trust-anchors
        - mountPath: /var/run/linkerd/identity/end-entity
          name: identity-end-entity
        livenessProbe:
          httpGet:
            path: /ping
            port: 9990
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9990
          failureThreshold: 7
        {{- if .EnableHA }}
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
      volumes:
      - name: identity-trust-anchors
        configMap:
          name: linkerd-identity-trust-anchors
      - name: identity-issuer
        secret:
          secretName: linkerd-identity-issuer
{{end -}}
{{end -}}
